sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=orguser
    # REGISTRY_PASS=...
    - secret: "thisissecret"

script:
  - docker build --tag orguser/myimage1 .
  - docker run orguser/myawesometeam

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push orguser/myawesometeam
  on:
    branch: master

