sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=serlevki
    - REGISTRY_PASS=gangik228
    
script:
  - docker-compose up

after_script:
  - docker-compose build zabbix/zabbix-server-mysql  

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  skip_cleanup: true
  script: docker push selevki/myawesometeam 
  on:
    branch: master

