
sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=serlevki
    - REGISTRY_PASS=gangik228
    
script:
  - docker-compose build

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  skip_cleanup: true
  script: docker push serlevki/myawesometeam
  on:
    branch: master

script:
  - docker-compose ps
