sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER="<account>"
    - REGISTRY_PASS="<password dockrhub>"
    

script:
  - docker-compose up 

after_script:
  - docker-compose build travicci_zabbix_1  

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  skip_cleanup: true
  script: bash docker_push
  on:
    branch: master


