
sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=serlevki
    - REGISTRY_PASS=gangik228
    - secret: "<thisissecret>"

script:
  - docker-compose up   

after_script:
  - docker-compose build

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push serlevki/myawesometeam
  on:
    branch: master

