language: bash
sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=serlevki
    - REGISTRY_PASS=gangik228
    - secret: "<thisissecret>"

script:
  - docker-compose up 
  - docker run serlevki/myawesometeam

after_script:
  - docker images
  
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push serlevki/myawesometeam
  on:
    branch: master

script:
  - sleep 1000
  - echo "the build was done"
