language: bash
sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=serlevki
    - REGISTRY_PASS=gangik228
    - secret: "<thisissecret>"

script:
  - docker-compose up 
  

after_script:
  - docker images
  - docke run serlevki/myawesometeam

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  skip_cleanup: true
  provider: script
  script: docker push serlevki/myawesometeam
  on:
    branch: master

script:
  - docker ps -a
  - docker images

