language: bash
sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=serlevki
    - REGISTRY_PASS=gangik228
    - secret: "<thisissecret>"

script:
  - docker-compose up 

after_script:
  - docker images
  
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker-compose stop

deploy:
  provider: script
  script: docker push serlevki/myawesometeam
  on:
    branch: master

script:
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then make deploy; else make lint_the_things; fi
