version: '3.1'

services: 

 db:
   build: ./db
   restart: always
   environment:
     DB_SERVER_HOST: 'db'
     MYSQL_DATABASE: 'zabbix'
     MYSQL_USER: 'root'
     MYSQL_PASSWORD: 'root'
     MYSQL_ROOT_PASSWORD: 'root'
   entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8', '--collation-server=utf8_bin'] 

 javagw:
   build: ./javagw
   restart: always
   depends_on: 
     - db

 zabbix: 
   build: ./zabbix
   restart: always
   environment:
     DB_SERVER_HOST: 'db'
     MYSQL_DATABASE: 'root'
     MYSQL_USER: 'root'
     MYSQL_PASSWORD: 'root'
     MYSQL_ROOT_PASSWORD: 'root'
     ZBX_JAVAGATEWAY: 'zabbix-java-gateway'
   ports:
     - 10051:10051
   depends_on: 
     - db
     - javagw

 web: 
  build: ./web
  image: serlevki/myawesometeam
  restart: always
  environment:
     DB_SERVER_HOST: 'db'
     MYSQL_DATABASE: 'root'
     MYSQL_USER: 'root'
     MYSQL_PASSWORD: 'root'
     MYSQL_ROOT_PASSWORD: 'root'
  ports:
    - 89:80
  depends_on: 
    - db
    - javagw
    - zabbix
 
 adminer:
  build: ./adminer
  restart: always
  ports:
    - 6080:8080
